<!DOCTYPE html>
<html lang="en">
  <head>
        <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=endge, chrome=IE8" />
    <meta name="viewport" content="initial-scale=1.0, width=device-width, user-scalable=no" />
    <title> Exceptions for Go as a Library </title>
    <link href='http://fonts.googleapis.com/css?family=Alice' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Share+Tech+Mono' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Lora:400,400italic,700,700italic' rel='stylesheet' type='text/css'>
    <!--[if lte IE 8]><script type="text/javascript" src="http://hackthology.com/theme/js/html5shiv.js"></script><![endif]-->
    <link rel="stylesheet" type="text/css" href="http://hackthology.com/theme/css/skeleton.css" />
    <link rel="stylesheet" type="text/css" href="http://hackthology.com/theme/css/theme.css" />
    <link rel="shortcut icon" type="image/png" href="http://hackthology.com/favicon.png" />
    <!--[if lte IE 8]><link rel="shortcut icon" type="image/x-icon" href="http://hackthology.com/favicon.ico" /><![endif]-->
    <link rel="alternate" type="application/atom+xml"
                           title="Hackthology — Flux Atom"
                           href="http://hackthology.com/" /> 
    <link rel ="alternate" type="application/rss+xml"
                           title="Hackthology — Flux RSS"
                           href="http://hackthology.com/feeds/rss.xml" /> 

    <meta name="author"   content="Tim Henderson" />
    <meta name="keywords" content="" />
    <link rel="stylesheet" media="not print" type="text/css" href="http://hackthology.com/theme/css/pygments.css" /> 
  </head>
  <body>
    <div id="page">
      <header id="page-head">
        <h1>
          <a href="http://hackthology.com/index.html">Hackthology</a>
        </h1>
        <div class="top-nav">
<ul>
    <li><a href="http://hackthology.com/pages/about.html">about</a></li>
    <li><a href="http://hackthology.com/pages/consulting.html">consulting</a></li>
    <li><a href="http://hackthology.com/pages/projects.html">projects</a></li>
    <li><a href="http://hackthology.com/pages/research.html">research</a></li>
    <li><a href="http://hackthology.com/pages/teaching.html">teaching</a></li>
</ul>
<ul>
    <li><a href="http://hackthology.com/feeds/rss.xml">rss-feed</a></li>
    <li><a href="https://github.com/timtadh">github</a></li>
    <li><a href="https://twitter.com/timtadh">twitter</a></li>
    <li><a href="https://plus.google.com/109232399292705173597">google+</a></li>
</ul></div>
      </header>
      
      <div id="page-body">

        <article class="post" id="page-main" role="main">
      <header class="post-header">
        <h1 class="full">
          <a rel="bookmark"
             href="http://hackthology.com/exceptions-for-go-as-a-library.html"
             title="perm link Exceptions for Go as a Library">
             Exceptions for Go as a Library
          </a>
        </h1>
        <div class="meta">
<!-- includes/article_meta.html -->
          <div class="meta">
            by <a href="http://hackthology.com/pages/about.html">Tim Henderson</a>
            <br/> <time datetime="2016-05-19T00:00:00-04:00">Thu 19 May 2016</time></div>        </div>
      </header>
      <div class="post-content"> 
        <p>Go (golang) lacks support for exceptions found in many other languages. There
are good reasons for Go to not include exceptions. For instance, by making
error handling explicit the programmer is forced to think concretely about
the correct action to take. Fined grained control over the handling of errors
using multiple return parameters is one of Go's strengths.</p>
<p>However, there are cases where Go programs do not universally benefit from
the explicit handling of errors. For instance, consider the following code:</p>
<div class="highlight"><pre><span></span><span class="kd">func</span> <span class="nx">DoStuff</span><span class="p">(</span><span class="nx">a</span><span class="p">,</span> <span class="nx">b</span><span class="p">,</span> <span class="nx">c</span> <span class="kd">interface</span><span class="p">{})</span> <span class="kt">error</span> <span class="p">{</span>
    <span class="nx">x</span><span class="p">,</span> <span class="nx">err</span> <span class="o">:=</span> <span class="nx">foo</span><span class="p">(</span><span class="nx">a</span><span class="p">)</span>
    <span class="k">if</span> <span class="nx">err</span> <span class="o">!=</span> <span class="kc">nil</span> <span class="p">{</span>
        <span class="k">return</span> <span class="nx">err</span>
    <span class="p">}</span>
    <span class="nx">y</span><span class="p">,</span> <span class="nx">err</span> <span class="o">:=</span> <span class="nx">bar</span><span class="p">(</span><span class="nx">b</span><span class="p">,</span> <span class="nx">x</span><span class="p">)</span>
    <span class="k">if</span> <span class="nx">err</span> <span class="o">!=</span> <span class="kc">nil</span> <span class="p">{</span>
        <span class="k">return</span> <span class="nx">err</span>
    <span class="p">}</span>
    <span class="nx">z</span><span class="p">,</span> <span class="nx">err</span> <span class="o">:=</span> <span class="nx">bax</span><span class="p">(</span><span class="nx">c</span><span class="p">,</span> <span class="nx">x</span><span class="p">,</span> <span class="nx">y</span><span class="p">)</span>
    <span class="k">if</span> <span class="nx">err</span> <span class="o">!=</span> <span class="kc">nil</span> <span class="p">{</span>
        <span class="k">return</span> <span class="nx">err</span>
    <span class="p">}</span>
    <span class="k">return</span> <span class="nx">baz</span><span class="p">(</span><span class="nx">x</span><span class="p">,</span> <span class="nx">y</span><span class="p">,</span> <span class="nx">z</span><span class="p">)</span>
<span class="p">}</span>
</pre></div>


<p>If Go had exceptions such code could be easily simplified:</p>
<div class="highlight"><pre><span></span><span class="kd">func</span> <span class="nx">DoStuff</span><span class="p">(</span><span class="nx">a</span><span class="p">,</span> <span class="nx">b</span><span class="p">,</span> <span class="nx">c</span> <span class="kd">interface</span><span class="p">{})</span> <span class="nx">throws</span> <span class="kt">error</span> <span class="p">{</span>
    <span class="nx">x</span> <span class="o">:=</span> <span class="nx">foo</span><span class="p">(</span><span class="nx">a</span><span class="p">)</span>
    <span class="nx">y</span> <span class="o">:=</span> <span class="nx">bar</span><span class="p">(</span><span class="nx">b</span><span class="p">,</span> <span class="nx">x</span><span class="p">)</span>
    <span class="nx">baz</span><span class="p">(</span><span class="nx">x</span><span class="p">,</span> <span class="nx">y</span><span class="p">,</span> <span class="nx">bax</span><span class="p">(</span><span class="nx">c</span><span class="p">,</span> <span class="nx">x</span><span class="p">,</span> <span class="nx">y</span><span class="p">)</span>
<span class="p">}</span>
</pre></div>


<h3>Adding Exceptions with a Library</h3>
<p>I created a <a href="https://github.com/timtadh/data-structures/exc">library</a> which
adds support for exceptions to the go programming langauge.</p>
<p><a href="https://godoc.org/github.com/timtadh/data-structures/exc"><img src="https://godoc.org/github.com/timtadh/data-structures/exc?status.svg" alt="GoDoc"></a></p>
<p>This library allow you to write go with exceptions and try-catch-finally
blocks. It is not appropriate for all situations but can simplify some
application code. Libraries and external APIs should continue to conform to
the Go standard of returning error values.</p>
<p>Here is an example of the <code>DoStuff</code> function where foo, bar and baz all throw
exceptions instead of returning errors. (We will look at the case where they
return errors that you want to turn into exceptions next). We want DoStuff to
be an public API function and return an error:</p>
<div class="highlight"><pre><span></span><span class="kd">func</span> <span class="nx">DoStuff</span><span class="p">(</span><span class="nx">a</span><span class="p">,</span> <span class="nx">b</span><span class="p">,</span> <span class="nx">c</span> <span class="kd">interface</span><span class="p">{})</span> <span class="kt">error</span> <span class="p">{</span>
    <span class="k">return</span> <span class="nx">exc</span><span class="p">.</span><span class="nx">Try</span><span class="p">(</span><span class="kd">func</span><span class="p">()</span> <span class="p">{</span>
        <span class="nx">x</span> <span class="o">:=</span> <span class="nx">foo</span><span class="p">(</span><span class="nx">a</span><span class="p">)</span>
        <span class="nx">y</span> <span class="o">:=</span> <span class="nx">bar</span><span class="p">(</span><span class="nx">b</span><span class="p">,</span> <span class="nx">x</span><span class="p">)</span>
        <span class="nx">baz</span><span class="p">(</span><span class="nx">x</span><span class="p">,</span> <span class="nx">y</span><span class="p">,</span> <span class="nx">bax</span><span class="p">(</span><span class="nx">c</span><span class="p">,</span> <span class="nx">x</span><span class="p">,</span> <span class="nx">y</span><span class="p">)</span>
    <span class="p">}).</span><span class="nx">Error</span><span class="p">()</span>
<span class="p">}</span>
</pre></div>


<h4>Catch Blocks</h4>
<p>Now let's consider the case where we want to catch the exception log and
reraise it:</p>
<div class="highlight"><pre><span></span><span class="kd">func</span> <span class="nx">DoStuff</span><span class="p">(</span><span class="nx">a</span><span class="p">,</span> <span class="nx">b</span><span class="p">,</span> <span class="nx">c</span> <span class="kd">interface</span><span class="p">{})</span> <span class="kt">error</span> <span class="p">{</span>
    <span class="k">return</span> <span class="nx">exc</span><span class="p">.</span><span class="nx">Try</span><span class="p">(</span><span class="kd">func</span><span class="p">()</span> <span class="p">{</span>
        <span class="nx">x</span> <span class="o">:=</span> <span class="nx">foo</span><span class="p">(</span><span class="nx">a</span><span class="p">)</span>
        <span class="nx">y</span> <span class="o">:=</span> <span class="nx">bar</span><span class="p">(</span><span class="nx">b</span><span class="p">,</span> <span class="nx">x</span><span class="p">)</span>
        <span class="nx">baz</span><span class="p">(</span><span class="nx">x</span><span class="p">,</span> <span class="nx">y</span><span class="p">,</span> <span class="nx">bax</span><span class="p">(</span><span class="nx">c</span><span class="p">,</span> <span class="nx">x</span><span class="p">,</span> <span class="nx">y</span><span class="p">)</span>
    <span class="p">}).</span><span class="nx">Catch</span><span class="p">(</span><span class="o">&amp;</span><span class="nx">exc</span><span class="p">.</span><span class="nx">Exception</span><span class="p">{},</span> <span class="kd">func</span><span class="p">(</span><span class="nx">t</span> <span class="nx">exc</span><span class="p">.</span><span class="nx">Throwable</span><span class="p">)</span> <span class="p">{</span>
        <span class="nx">log</span><span class="p">.</span><span class="nx">Print</span><span class="p">(</span><span class="nx">t</span><span class="p">)</span>
        <span class="nx">exc</span><span class="p">.</span><span class="nx">Rethrow</span><span class="p">(</span><span class="nx">t</span><span class="p">,</span> <span class="nx">exc</span><span class="p">.</span><span class="nx">Errorf</span><span class="p">(</span><span class="s">&quot;rethrow after logging&quot;</span><span class="p">))</span>
    <span class="p">}).</span><span class="nx">Error</span><span class="p">()</span>
<span class="p">}</span>
</pre></div>


<p>Rethrow will chain the Throwable <code>t</code> with the new <code>*Error</code> created such that
if/when the exception reaches the top level you know exactly how it was
created and where it was rethrown.</p>
<h4>Throwing Errors</h4>
<p>Ok, what about interacting with regular Go APIs which return errors? How can
we turn those errors into exceptions? The easy was is to use the
<code>ThrowOnError</code> function which is a sugar for:</p>
<div class="highlight"><pre><span></span><span class="k">if</span> <span class="nx">err</span> <span class="o">!=</span> <span class="kc">nil</span> <span class="p">{</span>
    <span class="nx">ThrowErr</span><span class="p">(</span><span class="nx">ErrorFrom</span><span class="p">(</span><span class="nx">err</span><span class="p">)</span>
<span class="p">}</span>
</pre></div>


<p>So converting out original <code>DoStuff</code> function we get</p>
<div class="highlight"><pre><span></span><span class="kd">func</span> <span class="nx">DoStuff</span><span class="p">(</span><span class="nx">a</span><span class="p">,</span> <span class="nx">b</span><span class="p">,</span> <span class="nx">c</span> <span class="kd">interface</span><span class="p">{})</span> <span class="p">{</span> <span class="c1">// Throws</span>
    <span class="nx">x</span><span class="p">,</span> <span class="nx">err</span> <span class="o">:=</span> <span class="nx">foo</span><span class="p">(</span><span class="nx">a</span><span class="p">)</span>
    <span class="nx">exc</span><span class="p">.</span><span class="nx">ThrowOnError</span><span class="p">(</span><span class="nx">err</span><span class="p">)</span>
    <span class="nx">y</span><span class="p">,</span> <span class="nx">err</span> <span class="o">:=</span> <span class="nx">bar</span><span class="p">(</span><span class="nx">b</span><span class="p">,</span> <span class="nx">x</span><span class="p">)</span>
    <span class="nx">exc</span><span class="p">.</span><span class="nx">ThrowOnError</span><span class="p">(</span><span class="nx">err</span><span class="p">)</span>
    <span class="nx">z</span><span class="p">,</span> <span class="nx">err</span> <span class="o">:=</span> <span class="nx">bax</span><span class="p">(</span><span class="nx">c</span><span class="p">,</span> <span class="nx">x</span><span class="p">,</span> <span class="nx">y</span><span class="p">)</span>
    <span class="nx">exc</span><span class="p">.</span><span class="nx">ThrowOnError</span><span class="p">(</span><span class="nx">err</span><span class="p">)</span>
    <span class="nx">exc</span><span class="p">.</span><span class="nx">ThrowOnError</span><span class="p">(</span><span class="nx">baz</span><span class="p">(</span><span class="nx">x</span><span class="p">,</span> <span class="nx">y</span><span class="p">,</span> <span class="nx">z</span><span class="p">))</span>
<span class="p">}</span>
</pre></div>


<p>This package also supports: catching user defined exceptions, catching
multiple exception types, <code>Close</code> which works like the "try with resources"
construct in Java 7+, (multiple) finally blocks, and a choice between
propogating exceptions with <code>Unwind</code> or retrieving the error/exception with
<code>Error</code> and <code>Exception</code> functions.</p>
<p>One Gotcha! The <code>Try()</code> function creates a <code>*Block</code> struct. To execute the
block you must either call: <code>Unwind</code>, <code>Error</code>, or <code>Exception</code>. <code>Unwind</code>
executes the block, if there is an exception coming out of the block it
continues to cause the program stack unwind. <code>Error</code> and <code>Exception</code> excute
the block, but return the exception as a value to deal with in the usual Go
way.</p>
<h4>Finally Blocks</h4>
<p>Finally blocks are a great feature of exceptions. They allow you to have a block
of code run unconditionally after a try and catch block even if there was an
unhandled exception or re-raised exception. In this example I use a finally
block to log the timing information of the DoStuff function.</p>
<div class="highlight"><pre><span></span><span class="kd">func</span> <span class="nx">DoStuff</span><span class="p">(</span><span class="nx">a</span><span class="p">,</span> <span class="nx">b</span><span class="p">,</span> <span class="nx">c</span> <span class="kd">interface</span><span class="p">{})</span> <span class="kt">error</span> <span class="p">{</span>
    <span class="nx">start</span> <span class="o">:=</span> <span class="nx">time</span><span class="p">.</span><span class="nx">Now</span><span class="p">()</span>
    <span class="k">return</span> <span class="nx">exc</span><span class="p">.</span><span class="nx">Try</span><span class="p">(</span><span class="kd">func</span><span class="p">()</span> <span class="p">{</span>
        <span class="nx">x</span> <span class="o">:=</span> <span class="nx">foo</span><span class="p">(</span><span class="nx">a</span><span class="p">)</span>
        <span class="nx">y</span> <span class="o">:=</span> <span class="nx">bar</span><span class="p">(</span><span class="nx">b</span><span class="p">,</span> <span class="nx">x</span><span class="p">)</span>
        <span class="nx">baz</span><span class="p">(</span><span class="nx">x</span><span class="p">,</span> <span class="nx">y</span><span class="p">,</span> <span class="nx">bax</span><span class="p">(</span><span class="nx">c</span><span class="p">,</span> <span class="nx">x</span><span class="p">,</span> <span class="nx">y</span><span class="p">)</span>
    <span class="p">}).</span><span class="nx">Catch</span><span class="p">(</span><span class="o">&amp;</span><span class="nx">exc</span><span class="p">.</span><span class="nx">Exception</span><span class="p">{},</span> <span class="kd">func</span><span class="p">(</span><span class="nx">t</span> <span class="nx">exc</span><span class="p">.</span><span class="nx">Throwable</span><span class="p">)</span> <span class="p">{</span>
        <span class="nx">log</span><span class="p">.</span><span class="nx">Print</span><span class="p">(</span><span class="nx">t</span><span class="p">)</span>
        <span class="nx">exc</span><span class="p">.</span><span class="nx">Rethrow</span><span class="p">(</span><span class="nx">t</span><span class="p">,</span> <span class="nx">exc</span><span class="p">.</span><span class="nx">Errorf</span><span class="p">(</span><span class="s">&quot;rethrow after logging&quot;</span><span class="p">))</span>
    <span class="p">}).</span><span class="nx">Finally</span><span class="p">(</span><span class="kd">func</span><span class="p">()</span> <span class="p">{</span>
        <span class="nx">end</span> <span class="o">:=</span> <span class="nx">time</span><span class="p">.</span><span class="nx">Now</span><span class="p">()</span>
        <span class="nx">log</span><span class="p">.</span><span class="nx">Printf</span><span class="p">(</span><span class="s">&quot;Do stuff took: %v&quot;</span><span class="p">,</span> <span class="nx">end</span><span class="p">.</span><span class="nx">Sub</span><span class="p">(</span><span class="nx">start</span><span class="p">))</span>
    <span class="p">}).</span><span class="nx">Error</span><span class="p">()</span>
<span class="p">}</span>
</pre></div>


<h4>Automatically Closing Resources</h4>
<p>One common situation is to open a resource (like a file) and want it to close no
matter what. In Go this is often accomplished with a <code>defer</code> function. However,
we can accomplish the same thing with finer granularity using the <code>Close</code>
function which acts like a <code>Try</code> but automatically closes a created resource
when the block exits:</p>
<div class="highlight"><pre><span></span><span class="nx">Close</span><span class="p">(</span><span class="kd">func</span><span class="p">()</span> <span class="nx">io</span><span class="p">.</span><span class="nx">Closer</span> <span class="p">{</span>
    <span class="nx">f</span><span class="p">,</span> <span class="nx">err</span> <span class="o">:=</span> <span class="nx">os</span><span class="p">.</span><span class="nx">Create</span><span class="p">(</span><span class="s">&quot;/tmp/wizard&quot;</span><span class="p">)</span>
    <span class="nx">ThrowOnError</span><span class="p">(</span><span class="nx">err</span><span class="p">)</span>
    <span class="k">return</span> <span class="nx">f</span>
<span class="p">},</span> <span class="kd">func</span><span class="p">(</span><span class="nx">c</span> <span class="nx">io</span><span class="p">.</span><span class="nx">Closer</span><span class="p">)</span> <span class="p">{</span>
    <span class="nx">f</span> <span class="o">:=</span> <span class="nx">c</span><span class="p">.(</span><span class="o">*</span><span class="nx">os</span><span class="p">.</span><span class="nx">File</span><span class="p">)</span>
    <span class="nx">_</span><span class="p">,</span> <span class="nx">err</span> <span class="o">:=</span> <span class="nx">f</span><span class="p">.</span><span class="nx">WriteString</span><span class="p">(</span><span class="s">&quot;wizardry&quot;</span><span class="p">)</span>
    <span class="nx">ThrowOnError</span><span class="p">(</span><span class="nx">err</span><span class="p">)</span>
<span class="p">}).</span><span class="nx">Unwind</span><span class="p">()</span>
</pre></div>


<p>In the above code, the file created in the first function will always be closed
at the end of the *Block even if WriteString had an error. This get more
interesting if you imagine passing the resource to other functions which could
throw exceptions.</p>
<h4>User Defined Exception Types</h4>
<p>To create a user defined exception simply create a struct which inherits from
the <code>exc.Exception</code> struct by embedding it as the first member.</p>
<div class="highlight"><pre><span></span><span class="kd">type</span> <span class="nx">MyException</span> <span class="kd">struct</span> <span class="p">{</span>
    <span class="nx">exc</span><span class="p">.</span><span class="nx">Exception</span>
<span class="p">}</span>
</pre></div>


<p>Then you can catch <em>MyException with </em>Exception. eg:</p>
<div class="highlight"><pre><span></span><span class="nx">exc</span><span class="p">.</span><span class="nx">Try</span><span class="p">(</span><span class="kd">func</span><span class="p">()</span> <span class="p">{</span>
    <span class="nx">Throw</span><span class="p">(</span><span class="o">&amp;</span><span class="nx">MyException</span><span class="p">{</span><span class="o">*</span><span class="nx">Errorf</span><span class="p">(</span><span class="s">&quot;My Exception&quot;</span><span class="p">).</span><span class="nx">Exception</span><span class="p">()})</span>
<span class="p">}).</span><span class="nx">Catch</span><span class="p">(</span><span class="o">&amp;</span><span class="nx">Exception</span><span class="p">{},</span> <span class="kd">func</span><span class="p">(</span><span class="nx">t</span> <span class="nx">Throwable</span><span class="p">)</span> <span class="p">{</span>
    <span class="nx">log</span><span class="p">.</span><span class="nx">Log</span><span class="p">(</span><span class="s">&quot;caught!&quot;</span><span class="p">)</span>
<span class="p">}).</span><span class="nx">Unwind</span><span class="p">()</span>
</pre></div>


<p>This should work with heirarchies of exceptions allowing your code to declare
specific exceptions for specific errors.</p>
<h2>Conclusion</h2>
<p>There are good reasons why Go does not include exceptions at the language level.
However, at times their absence can become annoying. So I created this little
library that adds them to Go. You probably shouldn't make public APIs based on
it, but it may help you write certain internal code more clearly. One clear use
case is during a refactor adding <code>Throw</code> call in a deep internal function which
should have always returned an error. Then at the entry points to the API simply
wrap up in a <code>Try().Catch().Error()</code> which would accomplish the same thing as
adding a returned error throughout the library.</p>
<p>I hope you enjoy this little experiment of mine and don't send me too much hate
mail! I know that exceptions are controversal in the Go community. This library
tries to demonstrate how close <code>panic</code> and <code>recover</code> are to exceptions and how
to emulate exceptions using <code>panic</code> and <code>recover</code>.</p>
<p>Now go read the docs:</p>
<p><a href="https://godoc.org/github.com/timtadh/data-structures/exc"><img src="https://godoc.org/github.com/timtadh/data-structures/exc?status.svg" alt="GoDoc"></a></p>
      </div>
      </article> <!-- /#page-main -->

      </div>  <!-- /#page-body -->

      <footer id="page-foot">
        <div class="bottom-nav">
<ul>
    <li><a href="http://hackthology.com/pages/about.html">about</a></li>
    <li><a href="http://hackthology.com/pages/consulting.html">consulting</a></li>
    <li><a href="http://hackthology.com/pages/projects.html">projects</a></li>
    <li><a href="http://hackthology.com/pages/research.html">research</a></li>
    <li><a href="http://hackthology.com/pages/teaching.html">teaching</a></li>
</ul>
<ul>
    <li><a href="http://hackthology.com/feeds/rss.xml">rss-feed</a></li>
    <li><a href="https://github.com/timtadh">github</a></li>
    <li><a href="https://twitter.com/timtadh">twitter</a></li>
    <li><a href="https://plus.google.com/109232399292705173597">google+</a></li>
</ul></div>
        <p>Copyright 2014 Tim Henderson. All Rights Reserved.</p>
      </footer>
    </div> <!-- /#page -->
    <script type="text/javascript">
      var _gaq = _gaq || [];
          _gaq.push(['_setAccount', 'UA-20145944-2']);
          _gaq.push(['_trackPageview']);
      (function() {
        var ga = document.createElement('script'); 
        ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();
    </script>
  </body>
</html>